global:

route:
  receiver: "signal"
  group_by: ["alertname"]
  group_wait: "5s"
  group_interval: "5m"
  repeat_interval: "5m"

receivers:
  - name: "signal"
    webhook_configs:
      - url: "http://127.0.0.1:10000/api/v3/alertmanager"
        send_resolved: true
