global:

route:
  receiver: "signal"
  group_by:
    - "alertname"
  group_wait: "5s"
  group_interval: "1m"
  repeat_interval: "1m"

receivers:
  - name: "signal"
    webhook_configs:
      - url: "http://10.88.0.1:10000/api/v3/alertmanager"
        send_resolved: true
