[bumpver]
current_version = "1.1.0"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true
pre_commit_hook = "bumpver_hook.sh"

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{ version }"'
]
"main.go" = [
    'const appVersion = "{ version }" // updated by bumpver'
]
"bumpver_hook.sh" = [
    '--tag { version }'
]
"README.md" = [
    'docker.io/schlauerlauer/alertmanager-webhook-signal:{ version }'
]
"Justfile" = [
    'VERSION := "{ version }" # updated by bumpver'
]